name: build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Test
        run: mvn clean verify -U
      - name: Change wrapper permissions
        run: chmod +x ./mvnw
      - name: build
        run: ./mvnw compile jib:dockerBuild
      - name: push
        run: docker push odfsoft/guess-game:latest

      - uses: actions/checkout@master
      - name: Publish to Docker hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: chaouredha/deploy-aws
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: MyApplicationName
          wait_for_deployment: true
          environment_name: Myapplicationname-env
          version_label: ${{ github.sha }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip

